### PR TITLE
BYOR: Add `vip app deploy`

### PR DESCRIPTION
**Pull request by rebeccahum**
## Description

Adding `vip app deploy` to VIP-CLI

## Steps to Test

1) In `src/bin/vip-app-deploy.js`, need to comment out for now:
```
await track( 'deploy_app_command_execute' );
		await track( 'deploy_app_command_execute' );
		await gates( app, env, fileMeta );
```
2) `node ./dist/bin/vip-app-deploy.js -a 5190 -e production ~/Desktop/skeleton.zip`

### CODE REVIEW

**Comment by mjangda** [comment]
@Crixu How well does `vip deploy app` fit in with the new IA for VIP-CLI? Should this be `vip app deploy` instead?

**Comment by mjangda** [comment]
Similarly, if we were to add a rollback command, would that be `vip app rollback`?

**Comment by Crixu** [comment]
I agree that `vip app deploy` is a better choice and makes sure we're moving in the right direction for the future

**Comment by rebeccahum** [comment]
I've changed it to `app deploy` -- I like having the idea of an `app rollback` as well.

**Review by WPprodigy — APPROVED** [review]

**Pull request merged**
